name: javascript-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, master]

permissions: write-all

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm run test-once

      - name: Process each commit
        run: |
          # Get the list of commits in the push
          commits=$(git rev-list HEAD ^HEAD~$GITHUB_SHA)
          
          # Iterate over each commit
          for commit in $commits; do
            echo "Processing commit $commit"

            # Checkout each commit
            git checkout $commit

            # Run Jest coverage report
            echo "Generating Jest coverage report for commit $commit"
            npx jest --coverage --coverageReporters=text-summary > coverage-summary.txt
            
            # Capture the coverage summary
            COVERAGE_OUTPUT=$(cat coverage-summary.txt)
            
            # Post coverage as comment for each commit
            echo "Posting coverage comment for commit $commit"
            if [[ -n "${{ github.event.pull_request.number }}" ]]; then
              gh pr comment ${{ github.event.pull_request.number }} --body "Coverage report for commit $commit: \n\n$COVERAGE_OUTPUT"
            else
              echo "No pull request number found. Skipping comment."
            fi
          done
        shell: bash

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        id: coverage
        with:
          output: report-markdown, comment

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
