name: javascript-CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, master]
    
permissions: write-all

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Recorre cada commit en el push
      - name: Process each commit
        run: |
          for commit in $(jq -r '.commits[].id' <<< "${{ toJson(github.event.commits) }}"); do
            echo "Processing commit $commit"
            
            # Puedes agregar pasos específicos para cada commit
            git checkout $commit

            # Ejecuta pruebas unitarias y de cobertura para cada commit
            echo "Running Unit Tests for commit $commit"
            npm run test-once
            
            echo "Generating Jest coverage report for commit $commit"
            npx jest --coverage

            # Agrega aquí otras acciones que quieras realizar para cada commit

          done
        shell: bash

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.2.6
        id: coverage
        with:
          output: report-markdown, comment

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}
